info:
  name: Mentor Hub
  description: A platform to connect mentors with engineers engaged in a life long learning journey.
  slug: mentorhub
  developer_cli: mh
  db_name: mentor_hub
  base_port: 8383

organization:
  name: Mentor Forge
  email: info@agile-learning-institute.com
  founded: 2026
  slug: mentor-forge
  git_host: https://github.com
  git_org: mentor-forge
  docker_host: ghcr.io
  docker_org: mentor-forge